name: frontend
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  translator: ^1.0.3+1

  flutter:
    sdk: flutter
  shadcn_flutter: ^0.0.34
  google_fonts: ^6.1.0

  #firebase database
  cloud_firestore: ^5.6.6

  firebase_core: ^3.13.0

  firebase_auth: ^5.5.2
  http: ^1.3.0

  provider: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_driver:
    sdk: flutter
  test: any
  mockito: ^5.4.6
  build_runner: ^2.4.15
  integration_test:
    sdk: flutter
  firebase_core_platform_interface: ^5.4.0

flutter:
  uses-material-design: true
