// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9xCai0hD9qTn8M109olVQc2T_2mF5JsI',
    appId: '1:292024245830:web:d081526f50e9c84b54f447',
    messagingSenderId: '292024245830',
    projectId: 'hodien-f5535',
    authDomain: 'hodien-f5535.firebaseapp.com',
    storageBucket: 'hodien-f5535.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNvZfuNKtk7MLy76olM5RjVetJFgOuE30',
    appId: '1:292024245830:android:66171d677e80d9fa54f447',
    messagingSenderId: '292024245830',
    projectId: 'hodien-f5535',
    storageBucket: 'hodien-f5535.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-rYQXqKS8FLnFM09OQHVQSZQ--sOvK6Q',
    appId: '1:292024245830:ios:2101697ef7f17a4254f447',
    messagingSenderId: '292024245830',
    projectId: 'hodien-f5535',
    storageBucket: 'hodien-f5535.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-rYQXqKS8FLnFM09OQHVQSZQ--sOvK6Q',
    appId: '1:292024245830:ios:2101697ef7f17a4254f447',
    messagingSenderId: '292024245830',
    projectId: 'hodien-f5535',
    storageBucket: 'hodien-f5535.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9xCai0hD9qTn8M109olVQc2T_2mF5JsI',
    appId: '1:292024245830:web:3d06c4f6ad9e658054f447',
    messagingSenderId: '292024245830',
    projectId: 'hodien-f5535',
    authDomain: 'hodien-f5535.firebaseapp.com',
    storageBucket: 'hodien-f5535.firebasestorage.app',
  );
}
